local mod = get_mod("Many Mission Terminal")

mod:add_global_localize_strings({
	loc_mod_mmterm_filter = {
		en = "Filters",
		["zh-cn"] = "筛选",
		ru = "Фильтры",
		["zh-tw"] = "篩選",
	},
})

return {
	mod_name = {
		en = "Many Mission Terminal",
		["zh-cn"] = "Many Mission Terminal",
		ru = "Терминал множества миссий",
		["zh-tw"] = "Many Mission Terminal",
	},
	mod_description = {
		en = "Shows every joinable mission on the mission board, with a filter panel and a sortable mission list.",
		["zh-cn"] = "在任务面板上显示所有可加入的任务，附带筛选面板和可排序的任务列表。",
		ru = "Many Mission Terminal - Показывает все доступные для присоединения миссии на доске миссий, с панелью фильтров и сортируемым списком.",
		["zh-tw"] = "在任務面板上顯示所有可加入的任務，附帶篩選面板和可排序的任務列表。",
	},
	cat_common = {
		en = "Standard",
		["zh-cn"] = "标准任务",
		ru = "Обычные",
		["zh-tw"] = "標準任務",
	},
	cat_story = {
		en = "Show Campaign Missions",
		["zh-cn"] = "显示战役任务",
		ru = "Показать миссии кампании",
		["zh-tw"] = "顯示戰役任務",
	},
	col_cond = {
		en = "COND",
		["zh-cn"] = "状况",
		ru = "УСЛ",
		["zh-tw"] = "狀況",
	},
	col_conds = {
		en = "CONDITIONS",
		["zh-cn"] = "环境状况",
		ru = "УСЛОВИЯ",
		["zh-tw"] = "環境狀況",
	},
	col_side = {
		en = "SIDE",
		["zh-cn"] = "支线",
		ru = "ДОП",
		["zh-tw"] = "支線",
	},
	col_time = {
		en = "TIME LEFT",
		["zh-cn"] = "剩余时间",
		ru = "ОСТАЛОСЬ",
		["zh-tw"] = "剩餘時間",
	},
	col_type = {
		en = "TYPE",
		["zh-cn"] = "类型",
		ru = "ТИП",
		["zh-tw"] = "類型",
	},
	cond_darkness = {
		en = "Lights Out",
		["zh-cn"] = "熄灯",
		ru = "Затемнение",
		["zh-tw"] = "熄燈",
	},
	cond_gas = {
		en = "Toxic Gas",
		["zh-cn"] = "毒气",
		ru = "Ядовитый газ",
		["zh-tw"] = "毒氣",
	},
	cond_hounds = {
		en = "Hunting Grounds",
		["zh-cn"] = "猎场",
		ru = "Охотничьи угодья",
		["zh-tw"] = "獵場",
	},
	cond_monsters = {
		en = "Monstrosities",
		["zh-cn"] = "巨兽",
		ru = "Чудовища",
		["zh-tw"] = "巨獸",
	},
	cond_mutants = {
		en = "Mutants",
		["zh-cn"] = "变种人",
		ru = "Мутанты",
		["zh-tw"] = "變種人",
	},
	cond_purge = {
		en = "Ventilation Purge",
		["zh-cn"] = "通风净化",
		ru = "Продувка вентиляции",
		["zh-tw"] = "通風淨化",
	},
	cond_resistance = {
		en = "Increased Resistance",
		["zh-cn"] = "抵抗增强",
		ru = "Усиленное сопротивление",
		["zh-tw"] = "抵抗增強",
	},
	cond_snipers = {
		en = "Snipers",
		["zh-cn"] = "狙击手",
		ru = "Снайперы",
		["zh-tw"] = "狙擊手",
	},
	cond_specials = {
		en = "Waves of Specials",
		["zh-cn"] = "特殊敌人潮",
		ru = "Волны спецов",
		["zh-tw"] = "特殊敵人潮",
	},
	cond_daemonhosts = {
		en = "Daemonhosts",
		["zh-cn"] = "恶魔宿主",
		ru = "Демонхосты",
		["zh-tw"] = "惡魔宿主",
	},
	cond_poxbursters = {
		en = "Poxbursters",
		["zh-cn"] = "瘟疫爆破者",
		ru = "Чумные взрывуны",
		["zh-tw"] = "瘟疫爆破者",
	},
	filter_group_category = {
		en = "MISSION TYPE",
		["zh-cn"] = "任务类型",
		ru = "ТИП МИССИИ",
		["zh-tw"] = "任務類型",
	},
	filter_group_condition = {
		en = "CONDITIONS",
		["zh-cn"] = "环境状况",
		ru = "УСЛОВИЯ",
		["zh-tw"] = "環境狀況",
	},
	filter_group_match = {
		en = "CONDITION MATCHING",
		["zh-cn"] = "条件匹配",
		ru = "СОВПАДЕНИЕ УСЛОВИЙ",
		["zh-tw"] = "條件匹配",
	},
	filter_group_side = {
		en = "SIDE OBJECTIVE",
		["zh-cn"] = "支线目标",
		ru = "ПОБОЧНАЯ ЗАДАЧА",
		["zh-tw"] = "支線目標",
	},
	filter_group_state = {
		en = "AVAILABILITY",
		["zh-cn"] = "可用状态",
		ru = "ДОСТУПНОСТЬ",
		["zh-tw"] = "可用狀態",
	},
	filter_match_any = {
		en = "Match any ticked condition",
		["zh-cn"] = "匹配任一勾选的状况",
		ru = "Совпадение по любому отмеченному условию",
		["zh-tw"] = "符合任一勾選的狀況",
	},
	filter_title = {
		en = "Filters",
		["zh-cn"] = "筛选",
		ru = "Фильтры",
		["zh-tw"] = "篩選",
	},
	group_board = {
		en = "Mission Board",
		["zh-cn"] = "任务面板",
		ru = "Доска миссий",
		["zh-tw"] = "任務面板",
	},
	msg_incompatible_mod = {
		en = "# also changes the mission board and is not compatible with Many Mission Terminal's board layout. Disable one of them.",
		["zh-cn"] = "# 同样会修改任务面板，与 Many Mission Terminal 的面板布局不兼容。请禁用其中一个。",
		ru = "# также изменяет доску миссий и несовместим с раскладкой доски Many Mission Terminal. Отключите один из них.",
		["zh-tw"] = "# 同樣會修改任務面板，與 Many Mission Terminal 的面板佈局不相容。請停用其中一個。",
	},
	msg_matchmaking_rejected = {
		en = "The backend refused that mission. Marked as expired.",
		["zh-cn"] = "后端拒绝了该任务，已标记为过期。",
		ru = "Сервер отклонил эту миссию. Отмечена как просроченная.",
		["zh-tw"] = "後端拒絕了該任務，已標記為過期。",
	},
	msg_past_horizon = {
		en = "Too old to join: # minutes past expiry. Missions stop accepting players about 180 minutes after they expire.",
		["zh-cn"] = "过旧无法加入：已过期 # 分钟。任务在过期约 180 分钟后不再接受玩家。",
		ru = "Слишком стара для входа: прошло # минут после истечения. Миссии перестают принимать игроков примерно через 180 минут после истечения срока.",
		["zh-tw"] = "過舊無法加入：已過期 # 分鐘。任務在過期約 180 分鐘後不再接受玩家。",
	},
	msg_reopen_board = {
		en = "Reopen the mission board to apply this change",
		["zh-cn"] = "重新打开任务面板以应用此更改",
		ru = "Откройте доску миссий заново, чтобы применить изменение",
		["zh-tw"] = "重新開啟任務面板以套用此變更",
	},
	show_all_missions = {
		en = "Show every mission on the board",
		["zh-cn"] = "在面板上显示所有任务",
		ru = "Показывать все миссии на доске",
		["zh-tw"] = "在面板上顯示所有任務",
	},
	tip_saved = {
		en = "Saved Mission",
		["zh-cn"] = "已保存的任务",
		ru = "Сохранённая миссия",
		["zh-tw"] = "已儲存的任務",
	},
	side_none = {
		en = "No Side Objective",
		["zh-cn"] = "无支线目标",
		ru = "Без побочной задачи",
		["zh-tw"] = "無支線目標",
	},
	state_expired = {
		en = "Recently Expired",
		["zh-cn"] = "最近过期",
		ru = "Недавно истёкшие",
		["zh-tw"] = "最近過期",
	},
	use_archive = {
		en = "Include recently expired missions (still joinable)",
		["zh-cn"] = "包含最近过期但仍可加入的任务",
		ru = "Показывать недавно истёкшие миссии (всё ещё доступные)",
		["zh-tw"] = "包含最近過期但仍可加入的任務",
	},
}
